version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/week9"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
    automerged_updates:
      - match:
          update_type: "version-update:semver-patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
